[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host = 'localhost'
Port = 49990
Protocol = 'http'
StartUpMsg = 'device tutorial started'
Timeout = 5000
ConnectRetries = 3
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consu'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

[Logging]
EnableRemote = false
File = './device-simple.log'

# Pre-define Devices
[[DeviceList]]
  Name = 'RandNum-Device01'
  Profile = 'RandNum-Device'
  Description = 'Random Number Generator Device'
  Labels = [ 'random', 'test' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = 'random'
      Port = '300'
  [[DeviceList.AutoEvents]]
    Resource = 'Random'
    OnChange = false
    Frequency = '10s'
